In [1]:
import pandas as pd
import numpy as np

In [2]:
customers = pd.read_csv('../data/Working Dataset/olist_customers_dataset.csv')

orders = pd.read_csv('../data/Working Dataset/olist_orders_dataset.csv')

order_items = pd.read_csv('../data/Working Dataset/olist_order_items_dataset.csv')

geolocation = pd.read_csv('../data/Working Dataset/olist_geolocation_dataset.csv')

order_payments = pd.read_csv('../data/Working Dataset/olist_order_payments_dataset.csv')

order_reviews = pd.read_csv('../data/Working Dataset/olist_order_reviews_dataset.csv')

products = pd.read_csv('../data/Working Dataset/olist_products_dataset.csv')

sellers = pd.read_csv('../data/Working Dataset/olist_sellers_dataset.csv')

productN_translation = pd.read_csv('../data/Working Dataset/product_category_name_translation.csv')

In [4]:
# customers.head()       # it gives all the rows and columns of the dataset
customers.shape        # it gives the number of rows and columns of the dataset
# customers.info()       # it gives the information about the dataset like number of rows, columns, data types, and memory usage
# customers.describe()   # it gives the statistical summary of the dataset like count, mean, std, min, 25%, 50%, 75%, and max
# customers.columns      # it gives the column names of the dataset
# customers.isnull().sum()  # it gives the number of missing values in each column of the dataset
# customers.duplicated().sum()  # it gives the number of duplicate rows in the dataset

(99441, 5)

In [ ]:
# orders.head()
# orders.shape   
# orders.info()  
# orders.describe()
# orders.columns
# orders.isnull().sum()
# orders.duplicated().sum()
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [50]:
# orders[orders['order_approved_at'].isnull()]['order_status'].value_counts()  # it gives the number of missing values in each column of the dataset
# orders[orders['order_delivered_carrier_date'].isnull()]['order_status'].value_counts()
orders[orders['order_delivered_customer_date'].isnull()]['order_status'].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [13]:
# order_items.head()
# order_items.shape
# order_items.info()
# order_items.describe()
# order_items.columns
# order_items.isnull().sum()
# order_items.duplicated().sum()  # it gives the number of duplicate rows in the dataset based on order_id and order_item_id

order_items[order_items['product_id'] == '5eb564652db742ff8f28759cd8d2652a']

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
7098,101157d4fae1c9fb74a00a5dee265c25,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-11 08:02:26,29.0,14.52
9233,1521c6bb7b1028154c8c67cf80fa809f,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-07 10:10:16,29.0,16.05
28715,415cfaaaa8cea49f934470548797fed1,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-07 10:35:19,29.0,14.52
28716,415cfaaaa8cea49f934470548797fed1,2,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-07 10:35:19,29.0,14.52
39299,595316a07cd3dea9db7adfcc7e247ae7,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-08-18 04:26:04,39.0,9.27
48424,6e150190fbe04c642a9cf0b80d83ee16,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-06-30 16:45:14,39.0,16.79
48980,6f497c40431d5fb0cfbd6c943dd29215,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-11 05:55:32,29.0,10.96
71134,a2456e7f02197951664897a94c87242d,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-06 11:50:09,29.0,24.84
73556,a7a43f469c0d7bdb0a23a82db125aefa,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-08-28 13:15:11,39.0,15.10
82767,bbfc7badbed2f1828e22b6d629201bd4,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-07-18 04:04:10,39.0,11.85
84199,bf49f84a0580ef6751e13357776b7ed9,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-07-09 21:35:18,39.0,15.10
85060,c1424efcde3c9e9febd9e1761667789e,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-14 02:45:36,29.0,14.52
93346,d38dcb503cd4ddc6ce7702552918bd8f,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-06-09 17:55:13,39.0,15.10
93347,d38dcb503cd4ddc6ce7702552918bd8f,2,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-06-09 17:55:13,39.0,15.10
97847,ddf16d77e858a32f36e10c289a28ef61,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-05-02 10:50:08,29.0,14.52
100495,e3daea0200104991cb979c2fcc509ae7,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-04-06 14:22:36,29.0,10.96
103715,eb855beb3ac99461f7a076b4c3652472,1,5eb564652db742ff8f28759cd8d2652a,4e922959ae960d389249c378d1c939f5,2017-03-30 16:03:46,29.0,14.52

In [9]:
# # geolocation.head()
# # geolocation.shape
# # geolocation.info()
# # geolocation.describe()
# # geolocation.columns
# # geolocation.isnull().sum()
# # geolocation.duplicated().sum()
# # geolocation[geolocation['geolocation_zip_code_prefix'] == 1037]
# # geolocation.head()
# geolocation['geolocation_zip_code_prefix'].nunique()
# geolocation.groupby('geolocation_zip_code_prefix').size().sort_values(ascending=False).head(20)
# geolocation['geolocation_zip_code_prefix'].value_counts().head(10)
geolocation[geolocation.duplicated()].head(10)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
15,1046,-23.546081,-46.644820,sao paulo,SP
44,1046,-23.546081,-46.644820,sao paulo,SP
65,1046,-23.546081,-46.644820,sao paulo,SP
66,1009,-23.546935,-46.636588,sao paulo,SP
67,1046,-23.546081,-46.644820,sao paulo,SP
72,1046,-23.545320,-46.644069,sao paulo,SP
79,1050,-23.549854,-46.643139,sao paulo,SP
80,1032,-23.540775,-46.635515,sao paulo,SP
82,1046,-23.546081,-46.644820,sao paulo,SP
86,1048,-23.547449,-46.640169,são paulo,SP

In [52]:
# products.head()
# products.shape
# products.info()
# products.describe()
# products.columns
products.isnull().sum()
# products.duplicated().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [10]:
products[products['product_category_name'].isnull()].isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                1
product_length_cm               1
product_height_cm               1
product_width_cm                1
dtype: int64

In [4]:
products[products['product_weight_g'].isnull()]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
products[products['product_length_cm'].isnull()]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
products[products['product_height_cm'].isnull()]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
products[products['product_width_cm'].isnull()]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
# sellers.head()
sellers.shape
# sellers.info()
# sellers.describe()
# sellers.columns
# sellers.isnull().sum()
# sellers.duplicated().sum()

(3095, 4)

In [24]:
# order_reviews.head()
order_reviews.shape
# order_reviews.info()
# order_reviews.describe()
# order_reviews.columns
# order_reviews.isnull().sum()
# order_reviews.duplicated().sum()

(99224, 7)

In [27]:
# order_payments.head()
order_payments.shape
# order_payments.info()
# order_payments.describe()
# order_payments.columns
# order_payments.isnull().sum()
# order_payments.duplicated().sum()

(103886, 5)

In [30]:
# productN_translation.head()
productN_translation.shape
# productN_translation.info()
# productN_translation.describe()
# productN_translation.columns
# productN_translation.isnull().sum()
# productN_translation.duplicated().sum()

(71, 2)